name: sc2-benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py38h709712a_0
  - freetype=2.10.4=h0708190_1
  - icu=67.1=he1b5a44_0
  - kiwisolver=1.3.1=py38h2531618_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - ncurses=6.3=h7f8727e_2
  - numpy=1.20.3=py38h9894fe3_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - pycocotools=2.0.2=py38hb5d20a5_2
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - readline=8.1=h27cfd23_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py38h497a2fe_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - compressai==1.1.9
    - packaging==21.3
    - pandas==1.3.4
    - pillow==8.4.0
    - pytorch-msssim==0.2.1
    - pytz==2021.3
    - pyyaml==6.0
    - scipy==1.7.2
    - seaborn==0.11.2
    - setuptools==59.2.0
    - timm==0.4.12
    - tomli==1.2.2
    - torch==1.10.0
    - torchdistill==0.3.0
    - torchvision==0.11.1
    - typing-extensions==4.0.0
prefix: /home/yoshitom/.conda/envs/sc2-benchmark
