datasets:
  pascal_voc:
    name: &dataset_name 'pascal_voc2012'
    key: 'VOCSegmentation'
    root: &root_dir '~/dataset'
    splits:
      val:
        dataset_id: &pascal_val !join [*dataset_name, '/val']
        kwargs:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_kwargs: &val_transform
            - key: 'CustomRandomResize'
              kwargs:
                min_size: 513
                max_size: 513
            - key: 'CustomToTensor'
              kwargs:
                converts_sample: True
                converts_target: True

models:
  model:
    name: 'NeuralInputCompressionSegmentationModel'
    kwargs:
      pre_transform:
        !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'sc2bench.transforms.misc.AdaptivePad'
                init:
                  kwargs:
                    padding_position: 'right_bottom'
                    returns_org_patch_size: True
                    fill: 0
                    factor: 64
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - key: 'FileSizeAnalyzer'
            kwargs:
              unit: 'KB'
      post_transform:
        !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'torchvision.transforms.Normalize'
                init:
                  kwargs:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225]
    compression_model:
      name: 'bmshj2018_factorized'
      kwargs:
        pretrained: True
        quality: 8
        metric: 'mse'
      ckpt: './resource/ckpt/input_compression/factorized_prior.pt'
    segmentation_model:
      name: 'deeplabv3_resnet50'
      kwargs:
        pretrained: True
        pretrained_backbone: True
        num_classes: 21
        aux_loss: True
      ckpt: 'https://github.com/yoshitomo-matsubara/torchdistill/releases/download/v0.2.8/pascal_voc2012-deeplabv3_resnet50.pt'

test:
  test_data_loader:
    dataset_id: *pascal_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'pascal_seg_eval_collate_fn'
