datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False

models:
  model:
    name: 'InputCompressionDetectionModel'
    params:
      codec_params:
        - type: 'PillowImageModule'
          params:
            format: 'JPEG'
            quality: 90
            returns_file_size: True
      analysis_config:
        analyzer_configs:
          - type: 'FileSizeAccumulator'
            params:
              unit: 'KB'
        analyzes_after_compress: True
      adaptive_pad_config:
      pre_transform_params:
      post_transform_params:
    detection_model:
      name: 'fasterrcnn_resnet50_fpn'
      params:
        pretrained: True
        progress: True
        pretrained_backbone: True
      ckpt: ''

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
